apiVersion: v1
kind: ServiceAccount
metadata:
  name: git-build-watcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: git-build-watcher
rules:
- apiGroups:
  - build.openshift.io
  resources:
  - buildconfigs
  verbs:
  - get
- apiGroups:
  - build.openshift.io
  resources:
  - buildconfigs/instantiate
  verbs:
  - create
- apiGroups:
  - build.openshift.io
  resources:
  - builds
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: git-build-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: git-build-watcher
subjects:
- kind: ServiceAccount
  name: git-build-watcher
