apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: git-build-watcher
  labels:
    app: git-build-watcher
    app.kubernetes.io/component: git-build-watcher
    app.kubernetes.io/instance: git-build-watcher
    app.kubernetes.io/part-of: openshift-bugzilla-tools
